# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
  System.debug: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |             
         mvn clean install
  displayName: Maven command line build

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'target/site' 
    artifactName: 'drop'

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: JaCoCo
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/target/site/jacoco'


